version: "3.9"

services:
  app:
    build: .
    container_name: ABED_SERVER
    working_dir: /app/Server
    volumes:
      - ./Server:/app/Server
      - ./logs:/var/log/app
    command: bun run src/index.ts
    ports:
      - "7890:7890"
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgres://abed_user:abed_password@postgres:5432/abed_db

  postgres:
    image: postgres:15
    container_name: ABED_POSTGRES
    ports:
      - "40316:5432"
    environment:
      POSTGRES_DB: abed_db
      POSTGRES_USER: abed_user
      POSTGRES_PASSWORD: abed_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  loki:
    image: grafana/loki:2.9.0
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml
      - ./loki-data:/loki

  promtail:
    image: grafana/promtail:2.9.0
    ports:
      - "9080:9080"
    volumes:
      - ./promtail-config.yaml:/etc/promtail/config.yaml
      - ./logs:/var/log/app:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command: -config.file=/etc/promtail/config.yaml -log.level=debug

  grafana:
    image: grafana/grafana:10.4.0
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana

volumes:
  grafana-data:
  postgres_data:
